build:
  image: smjoao/osto:latest
  script:
    - echo "Building solver"
    - cd solver
    - cmake -S . -B build
    - cmake --build build -j10
    - cmake --install build


test_numeric:
  image: smjoao/osto:latest
  script:
    - echo "Testing numeric"
    - cd numeric/tests
    - cmake -S . -B build
    - cmake --build build
    - build/numbers_test


test_state:
  image: smjoao/osto:latest
  script:
    - echo "Testing state"
    - cd state/tests
    - cmake -S . -B build
    - cmake --build build
    - build/state_test


# benchmark:
#   stage: test
#   image: gcc:latest
#   script:
#     - cd numeric/tests
#     - cmake -S . -B build
#     - cmake --build build
#     - build/numbers_test
    