
build:
  image: gcc:latest
  script:
    - echo "Building solver"
    - cmake -S . -B build
    - cmake --build build -j10
    - cmake --install build
  artifacts:
    paths:
      - bin/

test_numeric:
  image: gcc:latest
  script:
    - cd numeric/tests
    - cmake -S . -B build
    - cmake --build build
    - build/numbers_test

test_state:
  image: gcc:latest
  script:
    - cd numeric/tests
    - cmake -S . -B build
    - cmake --build build
    - build/numbers_test
    
benchmark:
  image: gcc:latest
  script:
    - cd numeric/tests
    - cmake -S . -B build
    - cmake --build build
    - build/numbers_test
    