stages:
  - prepare
  - build

# Define the build environment
# before_script:
#   - apt-get install libgmp-dev

# # Build and install Catch2 (from GitHub)
# install_catch2:
#   image: alpine
#   stage: prepare
#   script:
#     - git clone --branch v2.13.6 --single-branch https://github.com/catchorg/Catch2.git /Catch2
#     - cd /Catch2
#     - cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/usr/local
#     - cmake --build build --target install
#     - rm -rf /Catch2
#   artifacts:
#     paths:
#       - /usr/local/include/catch2

build:
  image: smjoao/osto:latest
  stage: build
  script:
    - echo "Building solver"
    - cmake -S . -B build
    - cmake --build build -j10
    - cmake --install build
  artifacts:
    paths:
      - bin/

test_numeric:
  image: smjoao/osto:latest
  stage: build
  script:
    - cd numeric/tests
    - cmake -S . -B build
    - cmake --build build
    - build/numbers_test

# test_state:
#   image: gcc:latest
#   stage: test
#   script:
#     - cd numeric/tests
#     - cmake -S . -B build
#     - cmake --build build
#     - build/numbers_test
    
# benchmark:
#   stage: test
#   image: gcc:latest
#   script:
#     - cd numeric/tests
#     - cmake -S . -B build
#     - cmake --build build
#     - build/numbers_test
    